baseURL = 'https://www.mazdak.xyz/'
languageCode = 'en-us'
title = 'Mazdak Nasab'
theme = 'hugo-clarity'

[menu]
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = -109

# social menu links
[[menu.social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/mazdakn"
[[menu.social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/mazdakn"
[[menu.social]]
  name = "rss"
  weight = 4
  url = "index.xml"
