baseURL = 'https://www.mazdak.xyz/'
languageCode = 'en-us'
title = 'Mazdak Nasab'
theme = 'poison'

[params]
    brand = "Mazdak Nasab"
    brand_image = "/images/mazdak.jpg"
    description = "Network System Engineer"
    github_url = "https://github.com/mazdakn"
    linkedin_url = "https://linkedin.com/in/mazdakn"
