baseURL = 'https://www.mazdak.tech/'
languageCode = 'en-us'
title = 'Mazdak Nasab'
theme = 'hugo-clarity'
disqusShortname = ""

[[menu.main]]
  name = "Home"
  url = ""
  weight = -110

[[menu.main]]
  name = "About"
  url = "about/"
  weight = -109

# social menu links
[[menu.social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/mazdakn"
[[menu.social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/mazdakn"
[[menu.social]]
  name = "rss"
  weight = 3
  url = "index.xml"
