[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/mazdakn"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/mazdakn"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
